# Generated by Django 2.0.1 on 2018-01-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(max_length=255)),
                ('year', models.DateTimeField()),
                ('genre', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('director', models.CharField(max_length=100)),
                ('casts', models.CharField(max_length=255)),
                ('intro', models.TextField()),
            ],
        ),
    ]
