# Generated by Django 2.0.1 on 2018-01-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema_Pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
