# Generated by Django 2.0.1 on 2018-01-13 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema_Pages', '0002_auto_20180110_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
    ]
