# Generated by Django 2.0.1 on 2018-01-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema_Pages', '0003_auto_20180113_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genres',
            new_name='gen',
        ),
    ]
