# Generated by Django 2.0.1 on 2018-01-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema_Pages', '0005_auto_20180113_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
