# Generated by Django 2.0.1 on 2018-01-13 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema_Pages', '0006_auto_20180113_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='directors',
        ),
    ]
