# Generated by Django 2.0.1 on 2018-01-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema_Pages', '0010_auto_20180113_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
